using System;
using System.Web;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.IO;

using myCore = frqtlib.Core;

namespace QlikViewExtensionServerWS.Models
{
    public class ExportRepository : IExportRepository
    {
        private void DeleteAllFromFolder()
        {
            DirectoryInfo d = new DirectoryInfo(("Web/cpcb"));
            foreach (FileInfo f in d.GetFiles())
            {
                if ((f.CreationTime.AddMinutes(2) < DateTime.Now))
                    File.Delete(f.FullName);
            }
        }

        public string saveAsPDF(string txt, string nme, int wid, double zoom)
        {
            myCore.Logging.log("ExportController saveAsPDF(string txt, string nme, string wid, string zoom) ...", myCore.LogType.Information);

            DeleteAllFromFolder();

            string id = DateTime.UtcNow.ToString("yyyyMMddHHmmssffff");

            System.Diagnostics.Process p = new System.Diagnostics.Process();
            p.StartInfo.FileName = "C:/Program Files (x86)/wkhtmltopdf/wkhtmltopdf.exe";
            p.StartInfo.UseShellExecute = false;

            string htmlFName = "Web/cpcb/" + "html-" + id + ".html";

            TextWriter tw = new StreamWriter(htmlFName);
            tw.WriteLine(txt);
            tw.Close();
            
            string pdfFName = "Web/cpcb/" + "pdf-" + id + ".pdf";
            string nm = nme;
            string ar = "--zoom " + zoom + " --page-size A4 --encoding utf-8 --header-spacing 3 -O Landscape --header-center " + "\"Generated by " + nm + " the " + DateTime.Now.ToString() + "\"" + " \"" + htmlFName + "\"" + " \"" + pdfFName + "\"";

            myCore.Logging.log(ar, myCore.LogType.Information);

            p.StartInfo.Arguments = ar;
            p.Start();
            p.WaitForExit(10000);

            return "pdf-" + id + ".pdf";
        }

        public string saveAsImg(string txt, string nme, int wid)
        {
            myCore.Logging.log("ExportController saveAsIMG(string txt, string wid) ...", myCore.LogType.Information);

            DeleteAllFromFolder();

            string id = DateTime.UtcNow.ToString("yyyyMMddHHmmssffff");

            System.Diagnostics.Process p = new System.Diagnostics.Process();
            p.StartInfo.FileName = "C:/Program Files (x86)/wkhtmltopdf/wkhtmltoimage.exe";
            p.StartInfo.UseShellExecute = false;

            string htmlFName = "Web/cpcb/" + "html-" + id + ".html";

            TextWriter tw = new StreamWriter(htmlFName);
            tw.WriteLine(txt);
            tw.Close();

            string imgFName = "Web/cpcb/" + "img-" + id + ".jpg";
            string nm = nme;
            string ar = "--encoding utf-8 --quality 100 --width " + wid + " " + "\"" + htmlFName + "\"" + " \"" + imgFName + "\"";

            myCore.Logging.log(ar, myCore.LogType.Information);

            p.StartInfo.Arguments = ar;
            p.Start();
            p.WaitForExit(10000);

            return "img-" + id + ".jpg";
        }
    }
}